import Footer from "./Components/Footer"
import Navbar from "./Components/Navbar"
import '@/app/styles/globals.css'
import { Suspense } from "react"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">

      <body>
       <Navbar/>
       <Suspense>
        {children}
        </Suspense>
        <Footer/>
        </body>
    </html>
  )
}
